# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171004_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.ImageField(upload_to='photos', verbose_name='My Photo')),
            ],
        ),
    ]
