# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171022_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=b'chandra2khadka@gmail.com', max_length=254),
        ),
    ]
